name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  ROOT_KEY: "tprv8ZgxMBicQKsPeb6rodrmEXb1zRucvxYJgTKDhqQkZtbz8eY4Pf2EgbsT2swBXnnbDPQChQeFrFqHN72yFxzKfFAVsHdPeRWq2xqyUT2c4wH"
  SOCKET_PORT: "10000"
  GRPC_IP: "localhost"
  GRPC_PORT: "23432"
  SIGNER_URL: "https://localhost:10000"
  PG_URL: "postgres://postgres:postgres@localhost:5432/postgres"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: node
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "28.x"

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build -p starknet-payment-indexer --all-targets --all-features
          cargo build -p db-node --all-targets --all-features
          cargo build -p nuts --all-targets --all-features
          cargo build -p starknet-types --all-targets --all-features
          cargo build -p node --all-targets --all-features
          cargo build -p starknet-payment-indexer-bin --all-targets --all-features
          cargo build -p signer --all-targets --all-features
          cargo build -p cli-wallet --all-targets --all-features
          cargo build -p wallet --all-targets --all-features

      - name: Run unit tests
        run: |
          cargo test -p starknet-payment-indexer --all-targets --all-features
          cargo test -p db-node --all-targets --all-features
          cargo test -p nuts --all-targets --all-features
          cargo test -p starknet-types --all-targets --all-features
          cargo test -p node --all-targets --all-features
          cargo test -p starknet-payment-indexer-bin --all-targets --all-features
          cargo test -p signer --all-targets --all-features
          cargo test -p cli-wallet --all-targets --all-features
          cargo test -p wallet --all-targets --all-features

      - name: Run signer integration tests
        run: |
          cargo run --release --bin signer &
          SIGNER_RUN_PID=$!
          while ! echo exit | nc localhost $SOCKET_PORT; do sleep 1; done
          cargo test -p signer-tests
          kill $SIGNER_RUN_PID

      - name: Run node integration tests
        run: |
          cargo run --release --bin node --no-default -features &
          NODE_RUN_PID=$!
          while ! echo exit | nc localhost $GRPC_PORT; do sleep 1; done
          cargo test -p node-tests
          kill $NODE_RUN_PID
